
on:
  push:
    branches:
      - main
jobs:
  Build-Typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npx tsc
    
      
      
